local RandomScamNum = math.random(1200, 90000)
local RandomWait1 = math.random(4, 10)
local RandomWait2 = math.random(6, 14)
local RandomWait3 = math.random(10, 18)
local RandomWait4 = math.random(6, 12)
local RandomWait5 = math.random(5, 11)
print("Generating Robux Number For You...")
wait(RandomWait1)
print("Your Robux addition amount is", RandomScamNum)
wait(RandomWait5)
print("Hacking Roblox Server To Add Robux To You...")
wait(RandomWait2)
print("Changing Your Robux Trade History, This Might Take Few Moment")
wait(RandomWait3)
print("Erasing Robux Change History...")
wait(RandomWait4)
print("Your New Robux Might Take 1~2 Weeks To Be Useable Cause We Took Most Safety Way To Send Robux, We Called It <Package Bux>")
wait(2)
print("Also Don't Worry About Your Account Get Banned Cause Our Development Already Tried 10 Weeks Ago And Not Banned Yet So Enjoy Your Robux!")
